# Generated by Django 4.2.1 on 2023-05-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmarcaciones', '0002_alter_marcacionmodel_hora_marcacion_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacionmodel',
            name='fecha_marcacion_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marcacionmodel',
            name='fecha_marcacion_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
